# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

# exclude docs and static css
exclude: |
  (?x)^(
    scripts/.*|
    src/docs/_build|
    src/docs/mkdocs.yml|
    src/{{ cookiecutter.python_package_name }}/interface/assets/.*|
    src/{{ cookiecutter.python_package_name }}/interface/static/.*|
    src/tests/.*
  )$
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace # Trims trailing whitespace.
        args: [--markdown-linebreak-ext=md]
      - id: check-ast # Checks whether the files parse as valid python.
      - id: check-case-conflict # Checks for files that would conflict in case-insensitive filesystems.
      - id: check-json # Attempts to load all json files to verify syntax
      - id: check-merge-conflict # Check for files that contain merge conflict strings
      - id: check-xml # Attempts to load all xml files to verify syntax
      - id: check-toml # Attempts to load all toml files to verify syntax
      - id: check-yaml # Attempts to load all yaml files to verify syntax
        args: [--unsafe]
      - id: end-of-file-fixer # Makes sure files end in a newline and only a newline.
      - id: check-symlinks # Checks for symlinks which do not point to anything
      - id: no-commit-to-branch # Protect specific branches from direct checkins (`master` by default)
        stages: [commit]
      - id: debug-statements # Check for debugger imports and py37+ breakpoint() calls in python source
      - id: check-added-large-files # Prevent giant files from being committed

  - repo: https://github.com/Lucas-C/pre-commit-hooks.git
    rev: v1.5.5
    hooks:
      - id: remove-crlf # Replace CRLF end-lines by LF ones before committing
      - id: remove-tabs # Replace tabs by whitespaces before committing

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: python-use-type-annotations

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier # Autoformat yaml and markdown files
        types_or: [yaml, markdown]

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.16.0
    hooks:
      - id: pyupgrade
        name: pyupgrade
        args: [--py{{ cookiecutter.python_short_version }}-plus]

  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        language_version: python{{ cookiecutter.python_version }}

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.4
    hooks:
      - id: ruff
        language_version: python{{ cookiecutter.python_version }}

  - repo: local
    hooks:
      - id: import-linter
        name: import linter
        language: system
        types: [python]
        entry: poetry run invoke --search-root src backend.run-python-import-linter
        pass_filenames: false
        require_serial: true
      - id: dmypy
        name: dmypy
        language: system
        types: [python]
        entry: poetry run invoke --search-root src backend.run-python-mypy
        pass_filenames: false
        require_serial: true
      - id: fixit
        name: fixit
        language: system
        types: [python]
        entry: .hooks/invoke-xargs.sh backend.run-python-fixit-linter-on-paths
        files: src/.*
      - id: commitlint
        name: commitlint
        language: docker_image
        entry: commitlint/commitlint:latest
        args:
          [
            "--config",
            "./commitlint.config.js",
            "--edit",
            ".git/COMMIT_EDITMSG",
          ]
        pass_filenames: false
        stages: [commit-msg]
